TWToolkitLang = {
 updateAvailable:"A new version of the script is available",
 updateDownload:"Download",
 open_number: "How many items do you want to use ?",
 open_info: "Progress...",
 open_result: "You get...",
 buy_number: "How many items do you want to buy ?",
 buy_item_value: "Purchase price",
 buy_total_value: "Total value",
 buy_confirm_title:"Purchase",
 buy_confirm_text1:"Are you sure you want to spend $",
 buy_confirm_text2:" to buy ",
 buy_error_location:"You have to be located in the town",
 buy_error_money:"You do not have enough money!",
 fbpopup_player:"Player",
 fbpopup_appoint_captain:"Promote to captain",
 fbpopup_appoint_private:"Appoint as private",
 fbpopup_appoint_recruit:"Appoint as recruit",
 fbpopup_appoint_reservist:"Appoint as reservist",
 fbpopup_appoint_traitor:"Mark as traitor",
 fbpopup_error_rank:"You can\'t demote fighters of the same or higher rank.",
 fbpopup_error_self:"(And especially not yourself)",
 fbcemetery_emptymessage:"No fort battles have been initiated lately.",
 fbcemetery_head_nam:"Character",
 fbcemetery_head_tow:"Town",
 fbcemetery_head_shp:"Start HP",
 fbcemetery_head_ehp:"Health at the end of the battle",
 fbcemetery_head_fla:"Held the flag",
 fbcemetery_head_hco:"Hit count",
 fbcemetery_head_fco:"Missed shots",
 fbcemetery_head_dco:"Damage inflicted",
 fbcemetery_head_ohi:"Hits taken",
 fbcemetery_head_ofa:"Dodged shots",
 fbcemetery_head_odm:"Damage taken",
 fbcemetery_head_avd:"Average damage done",
 fbcemetery_head_okh:"Passed out during fight",
 fbcemetery_head_onl:"Rounds been online",
 fbcemetery_head_cri:"Critical hits",
 fbcemetery_resmessages:{ATTACKER_WIPED:'The fort survived! all attackers have fallen!',DEFENDER_WIPED:'The fort has fallen! All defenders have been defeated!',FINALROUND:'The fort stood the attack well! After the hard fight attackers had to step back.',FLAGLOST:'The fort has fallen. After the long fight the attackers got a hold of the flag and the defenders capitulated.'},
 fbcemetery_attcount:"%1 fighter has attacked the fort.",
 fbcemetery_attscount:"%1 fighters have attacked the fort.",
 fbcemetery_defcount:"%1 defender defended.",
 fbcemetery_defscount:"%1 defenders defended.",
 fbcemetery_attdied:"%1 attacker fell.",
 fbcemetery_attsdied:"%1 attackers fell.",
 fbcemetery_defdied:"%1 defender fell.",
 fbcemetery_defsdied:"%1 defenders fell.",
 fbcemetery_maneuver:"Luckily, this was just a training.",
 fbcemetery_back:"To the overview",
 fbinfo_total:"TOTAL",
 fbinfo_hit:"Hit count",
 fbinfo_missed:"Missed shots",
 fbinfo_gotshot:"Hits taken",
 fbinfo_dodge:"Dodged shots",
 fbinfo_totaldmg:"Damage inflicted (except KO)",
 fbinfo_lastdmg:"Last hit",
 fbinfo_resetselect:"Reset current selection",
 pref_labels:['Use lots of bags with a common product and cempasúchil cases ','Buy lots of items in the shops','More informations in the Fort Battle map\'s popup (health points and proximity)','Critical hits column in Cemetery','Hit count, missed hits, hits taken and dodge shots each round','Total damage and last hit in players\' descriptions - Total health points of a selection of players<','Show the id of every item','Export items from a profile to your notebook','Add a personalized list of recipients (follow the syntax name1;name2;name3) ','Alliances','Additional towns','Additional players','Players excluded'],
 pref_save:"Save",
 pref_save_success:"Your preferences have been saved !",
 pref_apply:"Apply and reload",
 pref:"Preferences",
buy_info:"Starting buying items...",
buy_success:"All the items were bought",
export_ids:"Export items to your notebook",
export_ids_success:"The items were successfully saved",
list_perso:"Personalized list",
edit:" Edit",
wait:"Please wait...",
list_error:"An error occured with a town name",
players_added:" players added !",
api_gui:"<img src='https://westfrs.innogamescdn.com//images/items/yield/toolbox.png?4'></br></br><strong>Some tools for The West </strong></br><a target='\_blank\' href='https://greasyfork.org/fr/scripts/13506'>Know more about it</a></i></br></br>Si you have any problem or suggestion, you can contact me at <a target='\_blank\' href='mailto:thathanka.tw@gmail.com'>thathanka.tw@gmail.com</a>, or on Greasyfork.",

}
