TWToolkitLang = {
 updateAvailable:"Una nueva versión del script está disponible",
 updateDownload:"Descargar",
 open_number: "¿Cuántos artículos quieres usar?",
 open_info: "Progreso...",
 open_result: "Obtienes...",
 buy_number: "¿Cuántos artículos quieres comprar?",
 buy_item_value: "Precio compra",
 buy_total_value: "Valor total",
 buy_confirm_title:"Compra",
 buy_confirm_text1:"¿Seguro que quieres gastar $?",
 buy_confirm_text2:" para comprar ",
 buy_error_location:"Tienes que estar localizado en la ciudad",
 buy_error_money:"¡No tienes bastante dinero!",
 fbpopup_player:"Jugador",
 fbpopup_appoint_captain:"Ascender a a capitán",
 fbpopup_appoint_private:"Designar como privado",
 fbpopup_appoint_recruit:"Designar como recluta",
 fbpopup_appoint_reservist:"Designar como reservista",
 fbpopup_appoint_traitor:"Marcar como traidor",
 fbpopup_error_rank:"No puedes degradas a los combatientes de igual o mayor rango.",
 fbpopup_error_self:"(Y especialemte nunca a tí mismo)",
 fbcemetery_emptymessage:"Ninguna batalla de fuerte ha sido iniciada últimamente.",
 fbcemetery_head_nam:"Carácter",
 fbcemetery_head_tow:"Ciudad",
 fbcemetery_head_shp:"Vida Inicial",
 fbcemetery_head_ehp:"Vida Final",
 fbcemetery_head_fla:"Bandera",
 fbcemetery_head_hco:"Nº Aciertos",
 fbcemetery_head_fco:"Nº Fallos",
 fbcemetery_head_dco:"Daño causado",
 fbcemetery_head_ohi:"Nº Aciertos recibidos",
 fbcemetery_head_ofa:"Nº Eludidos",
 fbcemetery_head_odm:"Daño recibido",
 fbcemetery_head_avd:"Daño promedio hecho",
 fbcemetery_head_okh:"Desmayados durante la lucha",
 fbcemetery_head_onl:"Rondas conectado",
 fbcemetery_head_cri:"Críticos",
 fbcemetery_resmessages:{ATTACKER_WIPED:'El fuerte sobrevivió! ¡todos los atacantes han caído!',DEFENDER_WIPED:'El fuerte ha caído! ¡Todos los defensores han sido derrotados!',FINALROUND:'El fuerte resistión bien el ataque! Después de la dura lucha los atacantes tuvieron que dar un paso atrás.',FLAGLOST:'El fuerte ha caído. Después de la larga lucha los atacantes tomaron la bandera y los defensores capitularon.'},
 fbcemetery_attcount:"%1 luchador ha atacado el fuerte.",
 fbcemetery_attscount:"%1 luchadores han atacado el fuerte.",
 fbcemetery_defcount:"%1 defensor defendió.",
 fbcemetery_defscount:"%1 defensores defendieron.",
 fbcemetery_attdied:"%1 atacante cayó.",
 fbcemetery_attsdied:"%1 atacantes cayeron.",
 fbcemetery_defdied:"%1 defensor cayó.",
 fbcemetery_defsdied:"%1 defensores cayeron.",
 fbcemetery_maneuver:"Afortunadamente ésto solo fue una maniobra.",
 fbcemetery_back:"Vista general",
 fbinfo_total:"TOTAL",
 fbinfo_hit:"Nº Aciertos",
 fbinfo_missed:"Nº Fallos",
 fbinfo_gotshot:"Nº Aciertos recibidos ",
 fbinfo_dodge:"Nº Eludidos",
 fbinfo_totaldmg:"Daño causado (excepto KO)",
 fbinfo_lastdmg:"Último acierto",
 fbinfo_resetselect:"Reiniciar la selección actual",
 pref_labels:['Usar montones de bolsas con producto común y cajas de cempasúchil','Comprar un montón de artículos en las tiendas','Más información en el desplegable del mapa de batalla (puntos de salud y proximidad)','Columna de críticos en el Cementerio','Nº Aciertos, nº fallos, nº aciertos recibidos y nº eludidos en cada ronda','Daño total y último acierto en la descripción del jugador - Puntos de salud total para una selección de jugadores<','Mostrar la Id de cada artículo','Exportar artículos desde su perfil a su libro de notas','Añadir una lista personalizada de destinatarios (seguir la sintaxis nombre1;nombre2;nombre3) ','Alianzas','Ciudades adicionales','Jugadores adicionales','Jugadores excluidos','Remind me to vote','Remind me to open the advent calendar'],
 pref_save:"Guardar",
 pref_save_success:"¡Tus preferencias han sido guardadas!",
 pref_apply:"Aplicar y recargar",
 pref:"Preferencias",
buy_info:"Comenzando a comprar artículos...",
buy_success:"Todos los artículos fueron comprados",
export_ids:"Exportar artículos a tu libro de notas",
export_ids_success:"Los artículos fueron guardados con éxito",
list_perso:"Lista personalizada",
edit:" Editar",
wait:"Por favor espere...",
list_error:"Un error ocurrió con el nombre de una ciudad",
players_added:" ¡jugadores añadidos!",
api_gui:"<img src='https://westfrs.innogamescdn.com//images/items/yield/toolbox.png?4'></br></br><strong>Algunas herramientas para The West </strong></br><a target='\_blank\' href='https://greasyfork.org/en/scripts/13506'>Conozca más sobre él</a></i></br></br>Si tienes algún problema o sugerencia, puedes contactar conmigo en <a target='\_blank\' href='mailto:thathanka.tw@gmail.com'>thathanka.tw@gmail.com</a>, o en Greasyfork.",
list_error_allys:"An error occured with an alliance name",
calendar:"Open your advent calendar !",
vote:"Vote for The West !",
}
