TWToolkitLang = {
 updateAvailable:"Une nouvelle version pour ce script est disponible",
 updateDownload:"Téléchager",
 open_number: "Combien voulez-vous en ouvrir ?",
 open_info: "Ouverture en cours...",
 open_result: "Vous avez obtenu...",
 buy_number: "Combien voulez-vous en acheter ?",
 buy_item_value: "Valeur d\'achat",
 buy_total_value: "Montant total",
 buy_confirm_title:"Achat",
 buy_confirm_text1:"Etes-vous vraiment sûr(e) de vouloir dépenser ",
 buy_confirm_text2:"$ pour acheter ",
 buy_error_location:"Tu dois être sur place !",
 buy_error_money:"Tu n'as pas assez d'argent !",
 fbpopup_player:"Joueur",
 fbpopup_appoint_captain:"Faire passer au rang de capitaine",
 fbpopup_appoint_private:"Nommer simple soldat",
 fbpopup_appoint_recruit:"Nommer bleusaille",
 fbpopup_appoint_reservist:"Nommer réserviste",
 fbpopup_appoint_traitor:"Marquer comme traître",
 fbpopup_error_rank:"Tu ne peux pas dégrader des combattants de rang supérieur ou de même rang.",
 fbpopup_error_self:"(Et encore moins toi-même)",
 fbcemetery_emptymessage:"En ce moment il n\'y a pas de batailles de fort de prévues.",
 fbcemetery_head_nam:"Nom",
 fbcemetery_head_tow:"Ville",
 fbcemetery_head_shp:"Points de vie au début",
 fbcemetery_head_ehp:"Points de vie après la bataille",
 fbcemetery_head_fla:"Gardé le drapeau",
 fbcemetery_head_hco:"Nombre de coups réussis",
 fbcemetery_head_fco:"Tirs ratés",
 fbcemetery_head_dco:"Dégâts causés",
 fbcemetery_head_ohi:"Coups reçus",
 fbcemetery_head_ofa:"Tirs esquivés",
 fbcemetery_head_odm:"Dégâts reçus",
 fbcemetery_head_avd:"Dégâts moyens causés par les armes",
 fbcemetery_head_okh:"Adversaires tombés dans les pommes",
 fbcemetery_head_onl:"Tours en ligne",
 fbcemetery_head_cri:"Nombre de coups critiques",
 fbcemetery_resmessages:{ATTACKER_WIPED:'Le fort a été gardé ! Tous les attaquants on été repoussés !',DEFENDER_WIPED:'Le fort est tombé ! Tous les défenseurs ont été battus !',FINALROUND:'Le fort a été gardé ! Les attaquants ont dû battre en retraite après une bataille acharnée !',FLAGLOST:'Le fort est tombé ! Les attaquants ont pu garder le drapeau et démoraliser les défenseurs dans une bataille acharnée !'},
 fbcemetery_attcount:"%1 attaquant a attaqué le fort.",
 fbcemetery_attscount:"%1 attaquants ont attaqué le fort.",
 fbcemetery_defcount:"Il y avait %1 défenseur.",
 fbcemetery_defscount:"Il y avait %1 défenseurs.",
 fbcemetery_attdied:"%1 attaquant est tombé au champ d\'honneur.",
 fbcemetery_attsdied:"%1 attaquants sont tombés au champ d\'honneur.",
 fbcemetery_defdied:"%1 défenseur est tombé au champ d\'honneur.",
 fbcemetery_defsdied:"%1 défenseurs sont tombés au champ d\'honneur.",
 fbcemetery_maneuver:"Heureusement, ce n\'était qu\'un entrainement.",
 fbcemetery_back:"Retour",
 fbinfo_total:"TOTAL",
 fbinfo_hit:"Tirs réussis",
 fbinfo_missed:"Tirs ratés",
 fbinfo_gotshot:"Coups reçus",
 fbinfo_dodge:"Coups esquivés",
 fbinfo_totaldmg:"Dégâts totaux (ceux des KO exclus)",
 fbinfo_lastdmg:"Dernier tir",
 fbinfo_resetselect:"Supprimer la sélection actuelle",
 pref_labels:['Ouverture multiple de sacs avec un produit commun et de caisses de roses d\'Inde',
  'Achat multiple dans les boutiques',
  'Affichage d\'une popup dans la carte de préparation à une bataille de fort (Points de vie et proximité du fort)',
  ' Colonne du nombre de coups critiques dans le cimetière',
  'Statistiques personnelles à chaque tour',
  'Dégâts totaux et dernier tir pour chaque joueur - Affichage du total de points de vie d\'une sélection de joueurs',
  'Afficher l\'id de chaque objet',
  'Exporter une tenue depuis le profil d\'un joueur vers son carnet de notes',
  'Ajouter un groupe de destinataires personnalisé (suivre la syntaxe nom1;nom2;nom3)',
  'Alliances',
  'Villes',
  'Joueurs supplémentaires',
  'Joueurs exclus',
  'Me rappeler de voter',
  'Me rappeler d\'ouvrir le calendrier de l\'avent'],
 pref_save:"Sauvegarder",
 pref_save_success:"Vos préférences ont bien été sauvegardées !",
 pref_apply:"Appliquer et actualiser",
 pref:"Préférences",
buy_info:"Achats en cours...",
buy_success:"Achats terminés !",
export_ids:"Exporter les items portés vers votre carnet de notes",
export_ids_success:"Les données ont été enregistrées dans votre carnet de notes",
list_perso:"Liste personnalisée",
edit:" Modifier",
wait:"Veuillez patienter...",
list_error:"Un problème est survenu : nom de ville erroné",
players_added:" joueurs ajoutés !",
api_gui:"<img src='https://westfrs.innogamescdn.com//images/items/yield/toolbox.png?4'></br></br><strong>Divers outils pour The West </strong></br><a target='\_blank\' href='https://greasyfork.org/fr/scripts/13506'>En savoir plus ?</a></i></br></br>Si vous rencontrez des problèmes ou avez des suggestions, vous pouvez me contacter via l'adresse <a target='\_blank\' href='mailto:thathanka.tw@gmail.com'>thathanka.tw@gmail.com</a>, sur Greasyfork ou <a target='\_blank\' href='https://forum.the-west.fr/private.php?do=newpm&u=15034'> sur ce forum.</a>",
list_error_allys:"Un problème est survenu : nom d'alliance erroné",
calendar:"Ouvre une case de ton calendrier de l'avent !",
vote:"Vote pour The West !",
}

TWToolkit.Preferences={};
TWToolkit.Preferences.pref_ids=[['use_items',0],['buy_items',0],['fb_popup',0],['critical_hits',0],['fb_hits',0],['fb_info',0],['ids_popup',0],['export_ids',0],['add_recipient',0],['allys',1],['towns',1],['add_players',1],['remove_players',1],['vote',0,false],['calendar',0,false]];
TWToolkit.Preferences.preferences_default={'use_items':true,'buy_items':true,'fb_popup':true,'critical_hits':true,'fb_hits':true,'fb_info':true,'ids_popup':true,'export_ids':true,'add_recipient':false,'allys':'','towns':'','add_players':'','remove_players':'','vote':true,'calendar':true};
