TWToolkit.Lang = {
 api_gui:"<img src='https://westfrs.innogamescdn.com//images/items/yield/toolbox.png?4'></br></br><i>• Ouverture multiple de sacs avec un produit commun</br>• Achat multiple dans les boutiques</br></br>• Affichage d\'une popup dans la carte de préparation à une bataille de fort</br>• Possibilité de modifier les grades depuis la carte</br></br>• Colonne du nombre de coups critiques dans le cimetière</br></br>• Informations supplémentaires lors des batailles de fort :<p style='margin-left:30px'> - Statistiques personnelles à chaque tour</br> - Dégâts totaux et dernier tir pour chaque joueur</br> - Affichage du total de PV d\'une sélection de joueurs</p></br><a target='\_blank\' href='https://forum.beta.the-west.net/private.php?do=newpm&u=4072'>En savoir plus ?</a></i>",
 updateAvailable:"Une nouvelle version pour ce script est disponible",
 updateDownload:"Téléchager",
 open_number: "Combien voulez-vous en ouvrir ?",
 open_info: "Ouverture en cours...",
 open_result: "Vous avez obtenu...",
 buy_number: "Combien voulez-vous en acheter ?",
 buy_item_value: "Valeur d\'achat",
 buy_total_value: "Montant total",
 buy_confirm_title:"Achat",
 buy_confirm_text1:"Etes-vous vraiment sûr(e) de vouloir dépenser ",
 buy_confirm_text2:"$ pour acheter ",
 buy_error_location:"Tu dois être sur place !",
 buy_error_money:"Tu n'as pas assez d'argent !",
 fbpopup_player:"Joueur",
 fbpopup_appoint_captain:"Faire passer au rang de capitaine",
 fbpopup_appoint_private:"Nommer simple soldat",
 fbpopup_appoint_recruit:"Nommer bleusaille",
 fbpopup_appoint_reservist:"Nommer réserviste",
 fbpopup_appoint_traitor:"Marquer comme traître",
 fbpopup_error_rank:"Tu ne peux pas dégrader des combattants de rang supérieur ou de même rang.",
 fbpopup_error_self:"(Et encore moins toi-même)",
 fbcemetery_emptymessage:"En ce moment il n\'y a pas de batailles de fort de prévues.",
 fbcemetery_head_nam:"Nom",
 fbcemetery_head_tow:"Ville",
 fbcemetery_head_shp:"Points de vie au début",
 fbcemetery_head_ehp:"Points de vie après la bataille",
 fbcemetery_head_fla:"Gardé le drapeau",
 fbcemetery_head_hco:"Nombre de coups réussis",
 fbcemetery_head_fco:"Tirs ratés",
 fbcemetery_head_dco:"Dégâts causés",
 fbcemetery_head_ohi:"Coups reçus",
 fbcemetery_head_ofa:"Tirs esquivés",
 fbcemetery_head_odm:"Dégâts reçus",
 fbcemetery_head_avd:"Dégâts moyens causés par les armes",
 fbcemetery_head_okh:"Adversaires tombés dans les pommes",
 fbcemetery_head_onl:"Tours en ligne",
 fbcemetery_head_cri:"Nombre de coups critiques",
 fbcemetery_resmessages:{ATTACKER_WIPED:'Le fort a été gardé ! Tous les attaquants on été repoussés !',DEFENDER_WIPED:'Le fort est tombé ! Tous les défenseurs ont été battus !',FINALROUND:'Le fort a été gardé ! Les attaquants ont dû battre en retraite après une bataille acharnée !',FLAGLOST:'Le fort est tombé ! Les attaquants ont pu garder le drapeau et démoraliser les défenseurs dans une bataille acharnée !'},
 fbcemetery_attcount:"%1 attaquant a attaqué le fort.",
 fbcemetery_attscount:"%1 attaquants ont attaqué le fort.",
 fbcemetery_defcount:"Il y avait %1 défenseur.",
 fbcemetery_defscount:"Il y avait %1 défenseurs.",
 fbcemetery_attdied:"%1 attaquant est tombé au champ d\'honneur.",
 fbcemetery_attsdied:"%1 attaquants sont tombés au champ d\'honneur.",
 fbcemetery_defdied:"%1 défenseur est tombé au champ d\'honneur.",
 fbcemetery_defsdied:"%1 défenseurs sont tombés au champ d\'honneur.",
 fbcemetery_maneuver:"Heureusement, ce n\'était qu\'un entrainement.",
 fbcemetery_back:"Retour",
 fbinfo_total:"TOTAL",
 fbinfo_hit:"Tirs réussis",
 fbinfo_missed:"Tirs ratés",
 fbinfo_gotshot:"Coups reçus",
 fbinfo_dodge:"Coups esquivés",
 fbinfo_totaldmg:"Dégâts totaux (ceux des KO exclus)",
 fbinfo_lastdmg:"Dernier tir",
 fbinfo_resetselect:"Supprimer la sélection actuelle",
}
