TWToolkitLang = {
 updateAvailable:"Hodor",
 updateDownload:" Hodor ",
 open_number: " Hodor, Hodor, Hodor, Hodor?",
 open_info: " Hodor...",
 open_result: " Hodor...",
 buy_number: " Hodor, Hodor, Hodor, Hodor?",
 buy_item_value: " Hodor ,Hodor ",
 buy_total_value: " Hodor Hodor ",
 buy_confirm_title:" Hodor ",
 buy_confirm_text1:" Hodor, Hodor, Hodor",
 buy_confirm_text2:" Hodor ",
 buy_error_location:" Hodor, Hodor, Hodor ",
 buy_error_money:" Hodor, Hodor, Hodor, Hodor!",
 fbpopup_player:" Hodor ",
 fbpopup_appoint_captain:" Hodor ",
 fbpopup_appoint_private:" Hodor ",
 fbpopup_appoint_recruit:" Hodor ",
 fbpopup_appoint_reservist:" Hodor ",
 fbpopup_appoint_traitor:" Hodor, Hodor ",
 fbpopup_error_rank:" Hodor, Hodor, Hodor Hodor Hodor.",
 fbpopup_error_self:"( Hodor)",
 fbcemetery_emptymessage:" Hodor, Hodor, Hodor, Hodor.",
 fbcemetery_head_nam:" Hodor ",
 fbcemetery_head_tow:" Hodor ",
 fbcemetery_head_shp:" Hodor”,
 fbcemetery_head_ehp:" Hodor, Hodor, Hodor, Hodor ",
 fbcemetery_head_fla:" Hodor ",
 fbcemetery_head_hco:" Hodor , Hodor ",
 fbcemetery_head_fco:" Hodor ",
 fbcemetery_head_dco:" Hodor , Hodor ",
 fbcemetery_head_ohi:" Hodor ",
 fbcemetery_head_ofa:" Hodor ",
 fbcemetery_head_odm:" Hodor ",
 fbcemetery_head_avd:" Hodor ",
 fbcemetery_head_okh:" Hodor ",
 fbcemetery_head_onl:" Hodor ",
 fbcemetery_head_cri:" Hodor ",
 fbcemetery_attcount:"%1 Hodor.",
 fbcemetery_attscount:"%1 Hodor.",
 fbcemetery_defcount:"%1 Hodor.",
 fbcemetery_defscount:"%1 Hodor.",
 fbcemetery_attdied:"%1 Hodor.",
 fbcemetery_attsdied:"%1 Hodor.",
 fbcemetery_defdied:"%1 Hodor.",
 fbcemetery_defsdied:"%1 Hodor.",
 fbcemetery_maneuver:" Hodor, Hodor, Hodor.",
 fbcemetery_back:" Hodor ",
 fbinfo_total:" Hodor ",
 fbinfo_hit:" Hodor ",
 fbinfo_missed:" Hodor ",
 fbinfo_gotshot:" Hodor ",
 fbinfo_dodge:" Hodor ",
 fbinfo_totaldmg:" Hodor",
 fbinfo_lastdmg:" Hodor ",
 fbinfo_resetselect:" Hodor ",
 pref_labels:[' Hodor ',' Hodor ',' Hodor’,' Hodor ' Hodor ', Hodor ',' Hodor ',' Hodor ',' Hodor ',' Hodor ',' Hodor ',' Hodor '],
 pref_save:" Hodor ",
 pref_save_success:" Hodor!",
 pref_apply:" Hodor ",
 pref:" Hodor ",
buy_info:" Hodor...",
buy_success:" Hodor ",
export_ids:" Hodor ",
export_ids_success:"Hodor ",
list_perso:" Hodor ",
edit:" Hodor ",
wait:" Hodor...",
list_error:" Hodor ",
players_added:" Hodor!",
api_gui:"<img src='https://westfrs.innogamescdn.com//images/items/yield/toolbox.png?4'></br></br><strong>Some tools for The West </strong></br><a target='\_blank\' href='https://greasyfork.org/en/scripts/13506'>Know more about it</a></i></br></br>If you have any problem or suggestion, you can contact me at <a target='\_blank\' href='mailto:thathanka.tw@gmail.com'>thathanka.tw@gmail.com</a>, or on Greasyfork.",
list_error_allys:"An error occured with an alliance name",
}
