TWToolkitLang = {
updateAvailable:"È disponibile una nuova versione dello script",
updateDownload:"Scarica",
open_number: "Quanti ne vuoi aprire ?",
open_info: "Apertura in corso.",
open_result: "Hai ottenuto...",
buy_number: "Quanti ne vuoi comprare ?",
buy_item_value: "Valore d\'acquisto",
buy_total_value: "Importo totale ",
buy_confirm_title:"Acquista",
buy_confirm_text1: "Sei davvero sicuro di voler spendere ",
buy_confirm_text2:"$ per acquistare ",
buy_error_location:"Devi essere sul posto !",
buy_error_money:"Non hai abbastanza soldi !",
fbpopup_player:"Giocatore ",
fbpopup_appoint_captain:"Passa a capitano",
fbpopup_appoint_private:"Nomina soldato",
fbpopup_appoint_recruit:"Nomina recluta",
fbpopup_appoint_reservist:"Nomina riserva",
fbpopup_appoint_traitor:"Segna come traditore",
fbpopup_error_rank:"Non puoi degradare combattenti di grado superiore o uguale al tuo",
fbpopup_error_self:"(e nemmeno te stesso)",
fbcemetery_emptymessage:"Al momento non ci sono battaglie in programma.",
fbcemetery_head_nam:"Nome",
fbcemetery_head_tow:"Città",
fbcemetery_head_shp:"Punti vita iniziali",
fbcemetery_head_ehp:"Punti vita dopo la battaglia",
fbcemetery_head_fla:"Turni in bandiera",
fbcemetery_head_hco:"Numero di colpi a segno",
fbcemetery_head_fco:"Colpi mancati",
fbcemetery_head_dco:"Danni causati",
fbcemetery_head_ohi:"Colpi ricevuti",
fbcemetery_head_ofa:"Colpi schivati",
fbcemetery_head_odm:"Danni subiti",
fbcemetery_head_avd:"Danno medio",
fbcemetery_head_okh:"Avversari svenuti",
fbcemetery_head_onl:"Turni online",
fbcemetery_head_cri:"Colpi critici",
fbcemetery_resmessages:{ATTACKER_WIPED:'Il forte è stato difeso! Tutti gli aggressori sono stati respinti!',DEFENDER_WIPED:'Il forte è caduto! Tutti i difensori sono stati sconfitti !',FINALROUND:'Il forte è stato difeso! Gli attaccanti si sono ritirati dopo una feroce battaglia !',FLAGLOST:'Il forte è caduto! Gli aggressori sono riusciti a conquistare la bandiera e a sconfiggere i difensori in una feroce battaglia !'},
fbcemetery_attcount:"%1 attaccante ha attaccato il forte.",
fbcemetery_attscount:"%1 attaccanti hanno attaccato il forte.",
fbcemetery_defcount:"C'era %1 difensore.",
fbcemetery_defscount:"C'erano %1 difensori.",
fbcemetery_attdied:"%1 attaccante è caduto in battaglia.",
fbcemetery_attsdied:"%1 attaccanti sono caduti in battaglia.",
fbcemetery_defdied:"%1 difensore è caduto in battaglia r.",
fbcemetery_defsdied:"%1 difensori sono caduti in battaglia .",
fbcemetery_maneuver:"Per fortuna non era che una manovra.",
fbcemetery_back:"Indietro",
fbinfo_total:"TOTALE",
fbinfo_hit:"Colpi a segno",
fbinfo_missed:"Colpi mancati",
fbinfo_gotshot:"Colpi ricevuti",
fbinfo_dodge:"Colpi totali",
fbinfo_totaldmg:"Danni totali (esclusi i KO)",
fbinfo_lastdmg:"Ultimo colpo",
fbinfo_resetselect:"Eliminare la selezione corrente",
pref_labels:['Apertura multipla di zaini e forzieri','Acquisti multipli nei negozi','Visualizzazione di un pop-up per la preparazione alla battaglia al forte (Punti vita e vicinanza al forte)',' Colonna numero di colpi critici al cimitero','Statistiche personali a ogni turno','Danni totali e ultimo tiro per ogni giocatore - Visualizzare i punti vita totali di un giocatore selezionato','Visualizzare l\'id di ogni oggetto','Esportare il profilo di un giocatore nel blocco note','Aggiungere un gruppo di destinatari personalizzato (seguire la sintassi nome1;nome2;nome3)','Alleanze','Città','Giocatori aggiunti','Giocatori esclusi','Remind me to vote','Remind me to open the advent calendar'],
pref_save:"Salva",
pref_save_success:"Le impostazioni sono state salvate !",
pref_apply:"Applica e aggiorna",
pref:"Preferenze",
buy_info:"Acquisto in corso...",
buy_success:"Acquisto terminato !",
export_ids:"Esportare gli elementi nel blocco note ",
export_ids_success:"I dati sono stati registrati nel blocco note",
list_perso:"Lista personalizzata",
edit:" Modifica",
wait:"Attendere...",
list_error:"Attenzione : nome città errato",
players_added:" giocatori aggiunti !",
api_gui:"<img src='https://westfrs.innogamescdn.com//images/items/yield/toolbox.png?4'></br></br><strong>Varie utilità per The West </strong></br><a target='\_blank\' href='https://greasyfork.org/en/scripts/13506'>Ne vuoi sapere di più?</a></i></br></br>Se avete problemi o suggerimenti, contattatemi all'indirizzo <a target='\_blank\' href='mailto:thathanka.tw@gmail.com'>thathanka.tw@gmail.com</a>, o su Greasyfork.",
list_error_allys:"Attenzione : nome alleanza errato",
calendar:"Open your advent calendar !",
vote:"Vote for The West !",
}
