TWToolkitLang = {
 updateAvailable:"Nowa wersja skryptu jest dostępna.",
 updateDownload:"Pobierz",
 open_number: "Ile sztuk chcesz otworzyć?",
 open_info: "Otwieranie w toku...",
 open_result: "Otrzymałeś...",
 buy_number: "Ile sztuk chcesz kupić?",
 buy_item_value: "Cena zakupu za sztukę",
 buy_total_value: "Cena całkowitego zakupu",
 buy_confirm_title:"Kupiłeś",
 buy_confirm_text1:"Jesteś pewien kupna? ",
 buy_confirm_text2:"$ potrzebne do kupna ",
 buy_error_location:"Musisz być w odpowiednim mieście!",
 buy_error_money:"Nie masz wystarczającej ilości pieniędzy!",
 fbpopup_player:"Gracz",
 fbpopup_appoint_captain:"Przejdź do kapitana",
 fbpopup_appoint_private:"Nadaj Szeregowego",
 fbpopup_appoint_recruit:"Nadaj Rekruta",
 fbpopup_appoint_reservist:"Nadaj rezerwistę",
 fbpopup_appoint_traitor:"Oznacz go jako zdrajcę!",
 fbpopup_error_rank:"Nie możesz zmienić rangi osobie z wyższą lub równą tobie randze.",
 fbpopup_error_self:"(Nie możesz zmienić swojej rangi)",
 fbcemetery_emptymessage:"Żadna bitwa ostatnio nie została zwołana.",
 fbcemetery_head_nam:"Nazwa",
 fbcemetery_head_tow:"Miasta",
 fbcemetery_head_shp:"Początkowe punkty życia",
 fbcemetery_head_ehp:"Aktuale punkty życia",
 fbcemetery_head_fla:" Przechwycona flaga",
 fbcemetery_head_hco:"Celne strzały",
 fbcemetery_head_fco:"Pudła",
 fbcemetery_head_dco:"Spowodowane obrażenia",
 fbcemetery_head_ohi:"Otrzymane strzały",
 fbcemetery_head_ofa:"Uniknięto strzałów",
 fbcemetery_head_odm:"Otrzymane obrażenia",
 fbcemetery_head_avd:"Łączne otrzymane obrażenia",
 fbcemetery_head_okh:"Spowodowane omdlenia",
 fbcemetery_head_onl:"On-line",
 fbcemetery_head_cri:"Ilość trafień krytycznych",
 fbcemetery_resmessages:{ATTAK ODPARTO: 'Wszyscy napastnicy zostali odparci!',FORT UPADŁ: 'Wszyscy obrońcy zostali pokonani !',CZAS SKOŃCZONY:'Fort został utrzymany. Napastnicy sobie poszli!',FLAGA ZDOBYTA:'Napastnicy zdobyli flagę!'},
 fbcemetery_attcount:"%1 atakujący zaatakował fort.",
 fbcemetery_attscount:"%1 atakujących zaatakowało fort.",
 fbcemetery_defcount:" %1Obrońca bronił.",
 fbcemetery_defscount:"%1 Obrońców broniło.",
 fbcemetery_attdied:"%1 Atakujący poległ.",
 fbcemetery_attsdied:"%1 Atakujących poległo.",
 fbcemetery_defdied:"%1 Obrońca poległ.",
 fbcemetery_defsdied:"%1 Obrońców poległo.",
 fbcemetery_maneuver:"To był tylko trening...",
 fbcemetery_back:"Powrót",
 fbinfo_total:"RAZEM",
 fbinfo_hit:"Trafione strzały",
 fbinfo_missed:"Chybione strzały",
 fbinfo_gotshot:"Przyjęte obrażenia",
 fbinfo_dodge:"Uniknięto strzałów",
 fbinfo_totaldmg:"Całkowite obrażenia (bez strzału powodującego omdlenie)",
 fbinfo_lastdmg:"Ostatni strzał",
 fbinfo_resetselect:"Anuluj aktualny wybór.",
 pref_labels:['Otwieranie wielu toreb.','Wielokrotny zakup w sklepie.',' Wyświetlanie informacji  podczas przygotowania do bitwy (punkty życia, bycie on-line)',' Dodatkowa rubryka na trafienia krytyczne w raporcie z bitwy.',' Indywidualne statystyki',' Suma zadanych obrażeń oraz łączne HP wybranych graczy.',' Pokaż ID każdego przedmiotu ',' Eksport profilu (ubrań) gracza do swojego notatnika. ','Dodaj dodatkową grupę odbiorców ','Sojusz','Miasto','Dodatkowa Osoba','Wykluczony Gracz'],
 pref_save:"Zapisz",
 pref_save_success:"Twoje preferencje zostały zapisane!",
 pref_apply:"Zapisz i odśwież",
 pref:"Preferencje",
buy_info:"Zakupy w drodze...",
buy_success:"Zakupy zrobione!",
export_ids:"Eksportuj ubranie gracza do swojego notatnika.",
export_ids_success:"Dane zostały zapisane w notatniku",
list_perso:"Niestandardowa Lista",
edit:" Edytuj",
wait:"Proszę czekać...",
list_error:"Błędna nazwa miasta",
players_added:"Gracz dodany!",
api_gui:"<img src='https://westfrs.innogamescdn.com//images/items/yield/toolbox.png?4'></br></br><strong>Różne dodatki do The-West </strong></br><a target='\_blank\' href='https://greasyfork.org/fr/scripts/13506'>Dowiedz się więcej</a></i></br></br> Jeśli masz propozycję lub jakiś problem możesz skontaktować się z twórcą  <a target='\_blank\' href='mailto:thathanka.tw@gmail.com'>thathanka.tw@gmail.com</a>, lub na Greasyfork",
}
