TWToolkitLang = {
 api_gui:"<img src='https://westfrs.innogamescdn.com//images/items/yield/toolbox.png?4'></br></br><i>• Abrir vários Sacos com Produto Comum</br>• Comprar vários itens na loja</br></br>• Mais informações em pop-up do mapa da batalha de Fort (pontos de saúde e proximidade)</br>• Você pode nomear jogadores deste mapa (usando o teclado)</br></br>• Tiros criticos no Cemitérios</br></br>• Adicionar algumas informações durante as batalhas de forte : (não compatível com TWeaker)<p style='margin-left:30px'> - Contagem de acertos, erros, tiros tomados e desvios em cada ronda</br> - Dano total e último tiro na descrição do jogador</br> - Pontos de saúde de uma seleção de jogadores</p></br><a target='\_blank\' href='https://greasyfork.org/en/scripts/13506'>Saiba mais...</a></i>",
 updateAvailable:"Uma nova versão do script está disponível",
 updateDownload:"Download",
 open_number: "Quantos itens você quer usar ?",
 open_info: "Progresso...",
 open_result: "Você obtém...",
 buy_number: "Quantos itens você quer comprar ?",
 buy_item_value: "Preço de compra",
 buy_total_value: "Valor total",
 buy_confirm_title:"Compra",
 buy_confirm_text1:"Tem certeza de que quer gastar $",
 buy_confirm_text2:" para comprar ",
 buy_error_location:"Você tem que estar na cidade",
 buy_error_money:"Você não tem dinheiro suficiente!",
 fbpopup_player:"Jogador",
 fbpopup_appoint_captain:"Promover a capitão",
 fbpopup_appoint_private:"Marcar como soldado",
 fbpopup_appoint_recruit:"Marcar como recruta",
 fbpopup_appoint_reservist:"Marcar como reservista",
 fbpopup_appoint_traitor:"Marcar como traidor",
 fbpopup_error_rank:"Você não pode rebaixar jogadores da mesma patente ou superior.",
 fbpopup_error_self:"(e especialmente nem a si próprio)",
 fbcemetery_emptymessage:"Nenhuma batalha de fort foi iniciada ultimamente.",
 fbcemetery_head_nam:"Personagem",
 fbcemetery_head_tow:"Cidade",
 fbcemetery_head_shp:"HP Inicial",
 fbcemetery_head_ehp:"Saúde ao término da batalha",
 fbcemetery_head_fla:"Segurou a bandeira",
 fbcemetery_head_hco:"Contagem de danos",
 fbcemetery_head_fco:"Erros",
 fbcemetery_head_dco:"Dano infligido",
 fbcemetery_head_ohi:"Danos recebidos",
 fbcemetery_head_ofa:"Tiros desviados",
 fbcemetery_head_odm:"Dano recebido",
 fbcemetery_head_avd:"Média dos danos",
 fbcemetery_head_okh:"Desmaiou durante a batalha",
 fbcemetery_head_onl:"Rondas online",
 fbcemetery_head_cri:"Tiros Críticos",
 fbcemetery_resmessages:{ATTACKER_WIPED:'O forte sobreviveu! Todos os atacantes caíram!',DEFENDER_WIPED:'O forte caiu! Todos os defensofres foram derrotados!',FINALROUND:'O forte sustentou o ataque! Depois de uma luta difícil, os atacantes recuaram.',FLAGLOST:'O forte caiu. Após uma longa batalha, os atacantes apossaram-se da bandeira e os defensores se renderam.'},
 fbcemetery_attcount:"%1 guerreiros atacaram o fort.",
 fbcemetery_attscount:"%1 guerreiros atacaram o fort.",
 fbcemetery_defcount:"%1 defensor defendeu.",
 fbcemetery_defscount:"%1 defensores defenderam.",
 fbcemetery_attdied:"%1 atacante caiu.",
 fbcemetery_attsdied:"%1 atacantes caíram.",
 fbcemetery_defdied:"%1 defensor caiu.",
 fbcemetery_defsdied:"%1 defensores caíram.",
 fbcemetery_maneuver:"Por sorte, isto foi apenas um treino.",
 fbcemetery_back:"Para a visão geral",
 fbinfo_total:"TOTAL",
 fbinfo_hit:"Acertos",
 fbinfo_missed:"Tiros perdidos",
 fbinfo_gotshot:"Danos sofridos",
 fbinfo_dodge:"Tiros desviados",
 fbinfo_totaldmg:"Dano infligido (exceto KO)",
 fbinfo_lastdmg:"Último tiro",
 fbinfo_resetselect:"Resetar seleção atual",
}
