TWToolkitLang = {
 api_gui:"<img src='https://westfrs.innogamescdn.com//images/items/yield/toolbox.png?4'></br></br><i>• Use um mesmo pacote diversas vezes</br>• Compre vários itens nas lojas</br></br>• Mais informações no painel de batalhas de fortes (saúde e proximidade)</br>• Você pode indicar jogadores desse mapa (utilizando o teclado))</br></br>• Coluna com 'danos críticos' no cemitério</br></br>• Adiciona algumas informações durante batalhas : (incompatível com TWeaker)<p style='margin-left:30px'> - Contagem de tiros tomados e esquivados, além dos que você errou e acertou o adversário </br> - Dano total e último acerto na descrição do jogador.</br> - Resultado da quantidade de saúde do jogador selecionado. </p></br><a target='\_blank\' href='https://greasyfork.org/en/scripts/13506'>Saiba mais</a></i>",
 updateAvailable:"Há uma nova versão disponível!",
 updateDownload:"Download",
 open_number: "Quantos itens deseja utilizar?",
 open_info: "Em andamento...",
 open_result: "Você conseguiu...",
 buy_number: "Quantos itens deseja comprar?",
 buy_item_value: "Preço de compra",
 buy_total_value: "Valor total",
 buy_confirm_title:"Comprar",
 buy_confirm_text1:"Tem certeza que deseja gastar $",
 buy_confirm_text2:" para comprar ",
 buy_error_location:"Você precisa estar na cidade",
 buy_error_money:"Você não tem dinheiro suficiente!",
 fbpopup_player:"Jogador",
 fbpopup_appoint_captain:"Promover a capitão.",
 fbpopup_appoint_private:"Apontar como privado.",
 fbpopup_appoint_recruit:"Nomear recruta.",
 fbpopup_appoint_reservist:"Nomear reservista.",
 fbpopup_appoint_traitor:"Apontar como traidor.",
 fbpopup_error_rank:"Você não pode rebaixar jogadores com o mesmo rank ou superior ao seu.",
 fbpopup_error_self:"(Muito menos você mesmo.)",
 fbcemetery_emptymessage:"Nenhuma batalha de forte foi iniciada recentemente.",
 fbcemetery_head_nam:"Jogador",
 fbcemetery_head_tow:"Cidade",
 fbcemetery_head_shp:"Saúde inicial",
 fbcemetery_head_ehp:"Saúde no final da batalha",
 fbcemetery_head_fla:"Segurou a bandeira",
 fbcemetery_head_hco:"Contagem de tiros",
 fbcemetery_head_fco:"Tiros perdidos",
 fbcemetery_head_dco:"Dano causado",
 fbcemetery_head_ohi:"Tiros tomados",
 fbcemetery_head_ofa:"Tiros desviados",
 fbcemetery_head_odm:"Dano tomado",
 fbcemetery_head_avd:"Dano médio realizado",
 fbcemetery_head_okh:"Desmaiou durante a batalha",
 fbcemetery_head_onl:"Rounds online",
 fbcemetery_head_cri:"Danos críticos",
 fbcemetery_resmessages:{ATTACKER_WIPED:'O forte sobreviveu! Todos os atacantes caíram!',DEFENDER_WIPED:'O forte caiu! Todos os defensores foram derrotados!',FINALROUND:'O forte resistiu bem. Depois de uma longa batalha, os atacantes tiveram de recuar',FLAGLOST:'O forte caiu. Após uma longa batalha, os atacantes seguraram a bandeira e os defensores renderam-se.'},
 fbcemetery_attcount:"%1 lutador atacou o forte.",
 fbcemetery_attscount:"%1 lutadores atacaram o forte.",
 fbcemetery_defcount:"%1 defensor defendeu.",
 fbcemetery_defscount:"%1 defensores defenderam.",
 fbcemetery_attdied:"%1 atacante caiu.",
 fbcemetery_attsdied:"%1 atacantes cairam.",
 fbcemetery_defdied:"%1 defensor caiu.",
 fbcemetery_defsdied:"%1 defensores cairam.",
 fbcemetery_maneuver:"Por sorte, isso era só um treinamento.",
 fbcemetery_back:"Para a Visão Geral",
 fbinfo_total:"TOTAL",
 fbinfo_hit:"Contagem de tiros",
 fbinfo_missed:"Tiros perdidos",
 fbinfo_gotshot:"Tiros tomados",
 fbinfo_dodge:"Tiros desviados",
 fbinfo_totaldmg:"Dano causado (exceto KO)",
 fbinfo_lastdmg:"Último tiro",
 fbinfo_resetselect:"Redefinir seleção atual",
}
