TWToolkitLang = {
 updateAvailable:"Uma nova versão do script está disponível",
 updateDownload:"Download",
 open_number: "Quantos itens você quer usar ?",
 open_info: "Progresso...",
 open_result: "Você obtém...",
 buy_number: "Quantos itens você quer comprar ?",
 buy_item_value: "Preço de compra",
 buy_total_value: "Valor total",
 buy_confirm_title:"Compra",
 buy_confirm_text1:"Tem certeza de que quer gastar $",
 buy_confirm_text2:" para comprar ",
 buy_error_location:"Você tem que estar na cidade",
 buy_error_money:"Você não tem dinheiro suficiente!",
 fbpopup_player:"Jogador",
 fbpopup_appoint_captain:"Promover a capitão",
 fbpopup_appoint_private:"Marcar como soldado",
 fbpopup_appoint_recruit:"Marcar como recruta",
 fbpopup_appoint_reservist:"Marcar como reservista",
 fbpopup_appoint_traitor:"Marcar como traidor",
 fbpopup_error_rank:"Você não pode rebaixar jogadores da mesma patente ou superior.",
 fbpopup_error_self:"(e especialmente nem a si próprio)",
 fbcemetery_emptymessage:"Nenhuma batalha de fort foi iniciada ultimamente.",
 fbcemetery_head_nam:"Personagem",
 fbcemetery_head_tow:"Cidade",
 fbcemetery_head_shp:"HP Inicial",
 fbcemetery_head_ehp:"Saúde ao término da batalha",
 fbcemetery_head_fla:"Segurou a bandeira",
 fbcemetery_head_hco:"Contagem de danos",
 fbcemetery_head_fco:"Erros",
 fbcemetery_head_dco:"Dano infligido",
 fbcemetery_head_ohi:"Danos recebidos",
 fbcemetery_head_ofa:"Tiros desviados",
 fbcemetery_head_odm:"Dano recebido",
 fbcemetery_head_avd:"Média dos danos",
 fbcemetery_head_okh:"Desmaiou durante a batalha",
 fbcemetery_head_onl:"Rondas online",
 fbcemetery_head_cri:"Tiros Críticos",
 fbcemetery_resmessages:{ATTACKER_WIPED:'O forte sobreviveu! Todos os atacantes caíram!',DEFENDER_WIPED:'O forte caiu! Todos os defensofres foram derrotados!',FINALROUND:'O forte sustentou o ataque! Depois de uma luta difícil, os atacantes recuaram.',FLAGLOST:'O forte caiu. Após uma longa batalha, os atacantes apossaram-se da bandeira e os defensores se renderam.'},
 fbcemetery_attcount:"%1 guerreiros atacaram o fort.",
 fbcemetery_attscount:"%1 guerreiros atacaram o fort.",
 fbcemetery_defcount:"%1 defensor defendeu.",
 fbcemetery_defscount:"%1 defensores defenderam.",
 fbcemetery_attdied:"%1 atacante caiu.",
 fbcemetery_attsdied:"%1 atacantes caíram.",
 fbcemetery_defdied:"%1 defensor caiu.",
 fbcemetery_defsdied:"%1 defensores caíram.",
 fbcemetery_maneuver:"Por sorte, isto foi apenas um treino.",
 fbcemetery_back:"Para a visão geral",
 fbinfo_total:"TOTAL",
 fbinfo_hit:"Acertos",
 fbinfo_missed:"Tiros perdidos",
 fbinfo_gotshot:"Danos sofridos",
 fbinfo_dodge:"Tiros desviados",
 fbinfo_totaldmg:"Dano infligido (exceto KO)",
 fbinfo_lastdmg:"Último tiro",
 fbinfo_resetselect:"Resetar seleção atual",
  pref_labels:['Use lots of bags with a common product and cempasúchil cases ','Buy lots of items in the shops','More informations in the Fort Battle map\'s popup (health points and proximity)','Critical hits column in Cemetery','Hit count, missed hits, hits taken and dodge shots each round','Total damage and last hit in players\' descriptions - Total health points of a selection of players<','Show the id of every item','Export items from a profile to your notebook','Add a personalized list of recipients (follow the syntax name1;name2;name3) ','Alliances','Additional towns','Additional players','Players excluded'],
 pref_save:"Save",
 pref_save_success:"Your preferences have been saved !",
 pref_apply:"Apply and reload",
 pref:"Preferences",
buy_info:"Starting buying items...",
buy_success:"All the items were bought",
export_ids:"Export items to your notebook",
export_ids_success:"The items were successfully saved",
list_perso:"Personalized list",
edit:" Edit",
wait:"Please wait...",
list_error:"An error occured with a town name",
players_added:" players added !",
api_gui:"<img src='https://westfrs.innogamescdn.com//images/items/yield/toolbox.png?4'></br></br><strong>Some tools for The West </strong></br><a target='\_blank\' href='https://greasyfork.org/en/scripts/13506'>Know more about it</a></i></br></br>Si you have any problem or suggestion, you can contact me at <a target='\_blank\' href='mailto:thathanka.tw@gmail.com'>thathanka.tw@gmail.com</a>, or on Greasyfork.",

}
